name: 'Regula'
description: 'Run regula'
inputs:
  terraform_directory:
    description: |
      Deprecated: use `input_path` instead.
      Directory where your terraform files are located.  Defaults to the root of
      your repository.
    required: false
  input_path:
    description: |
      Input path for regula.  This can either be a terraform directory, a
      terraform JSON plan, or a cloudformation template.  Defaults to the root
      of your repository.
    required: false
  rego_paths:
    description: |
      Paths passed in to the Rego interpreter.  You should include all paths
      where rules are located.  Defaults to the Regula built-in rules located
      at `/opt/regula/rules` and can be extended with repository-specific rules.
    required: false
    default: /opt/regula/rules
outputs:
  rules_passed:
    description: 'Number of passed rules'
  rules_failed:
    description: 'Number of failed rules'
  controls_passed:
    description: 'Number of passed controls'
  controls_failed:
    description: 'Number of failed controls'
runs:
  using: 'docker'
  image: 'Dockerfile'
